sudo: required
services:
- docker
language: python

env:
  global:
    - CIBW_ENVIRONMENT="DISPTOOLS_CUDA_SUPPORT=ON"
    - CIBW_MANYLINUX1_X86_64_IMAGE=martinopilia/disptools:1
    - CIBW_BUILD="cp35-manylinux1_x86_64 cp36-manylinux1_x86_64 cp37-manylinux1_x86_64"

script:
  # Build wheels
  - pip install cibuildwheel==0.12.0
  - cibuildwheel --platform linux --output-dir dist

  # Run Python tests
  - |
    docker run -v "$(pwd)":/mnt martinopilia/disptools:1 bash -c '
    set -xeo pipefail
    cd /mnt
    /opt/python/cp37-cp37m/bin/python -m venv /tmp/venv
    source /tmp/venv/bin/activate
    pip install codecov==2.0.15 itk SimpleITK scikit-image vtk ply dist/*cp37*.whl
    python -m coverage run -m unittest discover
    coverage xml -o coverage.xml
    deactivate
    '
  - whoami | xargs -I{} sudo chown -R {} .

  # Run C tests
  - mkdir build
  - cd build
  - cmake -DDISPTOOLS_COVERAGE=ON ..
  - make
  - ctest -VV
  - cd "${TRAVIS_BUILD_DIR}"
  - find . -type f -name '*.gcda' -exec gcov {} \;

after_success:
  - bash <(curl -s https://codecov.io/bash) -X gcov -X coveragepy

deploy:
  provider: pypi
  edge: true
  distributions: sdist
  cleanup: false
  on:
    tags: true
  username: __token__
  password: i9X+K73tRVb8aV0V6T7DompYAP78r6ggJD4wpx6vXML4hw6EOumR0XoGrPbO8rZDBHLHRN0s9xtT0WaOAaYP5Gj3VA1mez1JJJyPswUjufRHg22LHhEGXNucrdVq9t9JGQD9D+IBD+VbI2K2pnhywxH6Aq04UDcZ2BzK9hHe2eMnG/0GLXrYMkUt1odBi/HnOla0GPXVYRTD4nUXHUoTJuq3mBdIj8guY7hxAbYJKO/ZSObatHO075iI5AywnVMXfBEqUi+caVltx1Ehf3HAA8lgDJO0qYEtxGclocb7KNMOJsgK4TPv47s/KjdS6rzsNudkKA96Q2nqhAPnoi4fDybWEBbZ+WKjRkMwoRiiaaYXyW71tl7ba0Gmvnuv5W/4YxRlh3s3mhw/7kbhWDelw/c6fJO81aEyWW+JrW27EIfhkki6yCIScAjmXDI/TRTnlCjeIxVEnn+BrxKcEZDWjujcLKLCkBE5hjtKJqFHN59FeLP9LjFTLXseOWIXCXSWh9VZd9WLgs/MxJphBGAmOc5bf6XoEcrtG6MQwcg4cRcq+nL0pwkDtOvOWDmfjETwECUka3FdxWmDDUyMxUS+osCyEop9XoapKAJcKPus0VWv4JT67wdvnZJ+BLg4woXU31VERQQfsq7WY5166oXNOiMBz2W9D/+PXPybDR5LbHM=
