name: ChecksLinux

on:
  push:
  pull_request:
  release:
    types:
      - published

jobs:
  ValidateCodecov:
    runs-on: ubuntu-latest
    steps:

    - name: Checkout
      uses: actions/checkout@v4

    - name: Validate Codecov configuration
      shell: bash
      run: |
        curl --data-binary @.codecov.yml https://codecov.io/validate | tee codecov_validation
        head -n 1 codecov_validation | grep 'Valid!'

  TestC:
    runs-on: ubuntu-latest
    steps:

    - name: Checkout
      uses: actions/checkout@v4

    - name: Run C tests
      shell: bash
      run: |
        mkdir build
        cd build
        cmake -DDISPTOOLS_COVERAGE=ON ..
        make
        ctest -VV
        cd "${GITHUB_WORKSPACE}"
        find . -type f -name '*.gcda' -exec gcov {} \;

    - name: Upload coverage report
      uses: codecov/codecov-action@v4
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
        fail_ci_if_error: true
        verbose: true

  BuildWheels:
    runs-on: ubuntu-latest

    env:
      CIBW_ENVIRONMENT: "DISPTOOLS_CUDA_SUPPORT=ON CUDACXX=/usr/local/cuda/bin/nvcc"
      CIBW_BUILD: "cp310-manylinux_x86_64 cp311-manylinux_x86_64 cp312-manylinux_x86_64"
      CIBW_BEFORE_ALL: >
        yum-config-manager --add-repo https://developer.download.nvidia.com/compute/cuda/repos/rhel7/x86_64/cuda-rhel7.repo &&
        yum install --setopt=obsoletes=0 -y cuda-nvcc-11-2-11.2.152-1 cuda-cudart-devel-11-2-11.2.152-1 &&
        ln -s cuda-11.2 /usr/local/cuda
    steps:

    - name: Checkout
      uses: actions/checkout@v4

    - name: Install Python dependencies
      run: python -m pip install cibuildwheel==2.20.0

    - name: Build wheels
      run: python -m cibuildwheel --output-dir dist

    - name: Archive wheels
      uses: actions/upload-artifact@v4
      with:
        name: wheels
        path: dist/*.whl

    - name: Publish wheels
      if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags')
      uses: pypa/gh-action-pypi-publish@release/v1
      with:
        user: __token__
        password: ${{ secrets.PYPI_API_TOKEN }}

  TestPython:
    runs-on: ubuntu-latest
    needs: BuildWheels
    strategy:
      matrix:
        python-version: ['3.10', '3.11']
    env:
      PYTHON_VER: ${{ matrix.python-version }}
    steps:

    - name: Checkout
      uses: actions/checkout@v4

    - uses: actions/download-artifact@v4
      with:
        name: wheels

    - name: Display structure of downloaded files
      run: ls -R

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install Python dependencies
      run: |
        pip install --user codecov==2.1.13 itk==5.4.0 SimpleITK==2.4.0 scikit-image vtk==9.3.1 ply==3.11 *cp${PYTHON_VER//./}*.whl

    - name: Run Python tests
      shell: bash
      run: |
        python -m coverage run -m unittest discover
        coverage xml -o coverage.xml

    - name: Upload coverage report
      uses: codecov/codecov-action@v4
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
        fail_ci_if_error: true
        verbose: true
